import type {
  AtRiskStop,
  DashboardSummary,
  Outage,
  Provider,
  ProximityAlert,
  RouteStop,
} from "../types";

export const providers: Provider[] = [
  {
    id: "p1",
    name: "Carver Senior Meals",
    borough: "Manhattan",
    address: "1595 Lexington Ave, New York, NY 10029",
    lat: 40.7918,
    lng: -73.9445,
    seniorsServed: 412,
  },
  {
    id: "p2",
    name: "Morrisania Care Collective",
    borough: "Bronx",
    address: "1309 Fulton Ave, Bronx, NY 10456",
    lat: 40.8331,
    lng: -73.9023,
    seniorsServed: 638,
  },
  {
    id: "p3",
    name: "Bedford-Stuyvesant Elder Network",
    borough: "Brooklyn",
    address: "1368 Fulton St, Brooklyn, NY 11216",
    lat: 40.6809,
    lng: -73.9512,
    seniorsServed: 521,
  },
  {
    id: "p4",
    name: "Flushing Homebound Services",
    borough: "Queens",
    address: "136-65 41st Ave, Queens, NY 11355",
    lat: 40.7574,
    lng: -73.8301,
    seniorsServed: 357,
  },
  {
    id: "p5",
    name: "Concourse Wellness Dispatch",
    borough: "Bronx",
    address: "851 Grand Concourse, Bronx, NY 10451",
    lat: 40.8276,
    lng: -73.9229,
    seniorsServed: 489,
  },
];

export const outages: Outage[] = [
  {
    id: "o1",
    complaintNumber: "1236609",
    status: "ACTIVE",
    bin: "1085680",
    address: "1595 Lexington Ave, New York, NY 10029",
    borough: "Manhattan",
    zipCode: "10029",
    lat: 40.7921,
    lng: -73.9442,
    dateEntered: "2026-06-26",
    chronicOffender: true,
    singleElevator: false,
  },
  {
    id: "o2",
    complaintNumber: "1244871",
    status: "ACTIVE",
    bin: "2008912",
    address: "1320 Webster Ave, Bronx, NY 10456",
    borough: "Bronx",
    zipCode: "10456",
    lat: 40.8345,
    lng: -73.9051,
    dateEntered: "2026-06-27",
    chronicOffender: true,
    singleElevator: true,
  },
  {
    id: "o3",
    complaintNumber: "1245902",
    status: "ACTIVE",
    bin: "2011544",
    address: "871 Grand Concourse, Bronx, NY 10451",
    borough: "Bronx",
    zipCode: "10451",
    lat: 40.8281,
    lng: -73.9221,
    dateEntered: "2026-06-27",
    chronicOffender: false,
    singleElevator: true,
  },
  {
    id: "o4",
    complaintNumber: "1240118",
    status: "ACTIVE",
    bin: "3019287",
    address: "1375 Fulton St, Brooklyn, NY 11216",
    borough: "Brooklyn",
    zipCode: "11216",
    lat: 40.6812,
    lng: -73.9506,
    dateEntered: "2026-06-25",
    chronicOffender: false,
    singleElevator: false,
  },
  {
    id: "o5",
    complaintNumber: "1246330",
    status: "ACTIVE",
    bin: "4044501",
    address: "136-20 Roosevelt Ave, Queens, NY 11354",
    borough: "Queens",
    zipCode: "11354",
    lat: 40.7601,
    lng: -73.8312,
    dateEntered: "2026-06-27",
    chronicOffender: false,
    singleElevator: true,
  },
  {
    id: "o6",
    complaintNumber: "1239004",
    status: "ACTIVE",
    bin: "2009377",
    address: "1301 Fulton Ave, Bronx, NY 10456",
    borough: "Bronx",
    zipCode: "10456",
    lat: 40.8329,
    lng: -73.9031,
    dateEntered: "2026-06-26",
    chronicOffender: true,
    singleElevator: false,
  },
];

export const stops: RouteStop[] = [
  {
    id: "s1",
    routeId: "R-MN-04",
    sequence: 3,
    recipientName: "E. Alvarez",
    address: "1593 Lexington Ave, Apt 6B, New York, NY 10029",
    borough: "Manhattan",
    lat: 40.7919,
    lng: -73.9447,
    floor: 6,
    scheduledTime: "09:20",
    providerId: "p1",
  },
  {
    id: "s2",
    routeId: "R-BX-11",
    sequence: 1,
    recipientName: "R. Okafor",
    address: "1322 Webster Ave, Apt 11F, Bronx, NY 10456",
    borough: "Bronx",
    lat: 40.8347,
    lng: -73.9054,
    floor: 11,
    scheduledTime: "08:45",
    providerId: "p2",
  },
  {
    id: "s3",
    routeId: "R-BX-11",
    sequence: 4,
    recipientName: "M. Delgado",
    address: "873 Grand Concourse, Apt 9A, Bronx, NY 10451",
    borough: "Bronx",
    lat: 40.8279,
    lng: -73.9224,
    floor: 9,
    scheduledTime: "10:05",
    providerId: "p5",
  },
  {
    id: "s4",
    routeId: "R-BK-07",
    sequence: 2,
    recipientName: "G. Thompson",
    address: "1377 Fulton St, Apt 4C, Brooklyn, NY 11216",
    borough: "Brooklyn",
    lat: 40.6814,
    lng: -73.9509,
    floor: 4,
    scheduledTime: "09:50",
    providerId: "p3",
  },
  {
    id: "s5",
    routeId: "R-QN-02",
    sequence: 5,
    recipientName: "L. Nguyen",
    address: "136-22 Roosevelt Ave, Apt 7D, Queens, NY 11354",
    borough: "Queens",
    lat: 40.7603,
    lng: -73.8315,
    floor: 7,
    scheduledTime: "11:15",
    providerId: "p4",
  },
  {
    id: "s6",
    routeId: "R-BX-11",
    sequence: 6,
    recipientName: "S. Pierre",
    address: "1303 Fulton Ave, Apt 14G, Bronx, NY 10456",
    borough: "Bronx",
    lat: 40.8331,
    lng: -73.9034,
    floor: 14,
    scheduledTime: "10:40",
    providerId: "p2",
  },
];

export const alerts: ProximityAlert[] = [
  {
    id: "a1",
    stopId: "s1",
    outageId: "o1",
    distanceMiles: 0.02,
    severity: "warning",
    suggestedAction: "Confirm elevator status by phone before dispatch; lobby drop-off if out.",
  },
  {
    id: "a2",
    stopId: "s2",
    outageId: "o2",
    distanceMiles: 0.03,
    severity: "critical",
    suggestedAction: "Single-elevator building, 11th floor. Reassign to walk-up-capable worker.",
  },
  {
    id: "a3",
    stopId: "s3",
    outageId: "o3",
    distanceMiles: 0.04,
    severity: "critical",
    suggestedAction:
      "Single-elevator outage, 9th floor. Schedule wellness call + same-day re-route.",
  },
  {
    id: "a4",
    stopId: "s4",
    outageId: "o4",
    distanceMiles: 0.05,
    severity: "watch",
    suggestedAction: "4th floor, multi-elevator building. Monitor; proceed with standard route.",
  },
  {
    id: "a5",
    stopId: "s5",
    outageId: "o5",
    distanceMiles: 0.03,
    severity: "critical",
    suggestedAction: "Single-elevator outage, 7th floor. Notify recipient; prepare backup carrier.",
  },
  {
    id: "a6",
    stopId: "s6",
    outageId: "o6",
    distanceMiles: 0.04,
    severity: "warning",
    suggestedAction: "Chronic-offender building, 14th floor. Verify access before 10:40 stop.",
  },
];

export const dashboardSummary: DashboardSummary = {
  activeOutages: outages.filter((o) => o.status === "ACTIVE").length,
  atRiskStops: alerts.length,
  providersAffected: 5,
  chronicOffenders: outages.filter((o) => o.chronicOffender).length,
  singleElevatorBuildings: outages.filter((o) => o.singleElevator).length,
  heatRiskMultiplier: 1.2,
  lastIngestAt: "2026-06-27T13:35:00-04:00",
  boroughBreakdown: [
    { borough: "Bronx", activeOutages: 3, atRiskStops: 3, chronicOffenders: 2 },
    { borough: "Manhattan", activeOutages: 1, atRiskStops: 1, chronicOffenders: 1 },
    { borough: "Brooklyn", activeOutages: 1, atRiskStops: 1, chronicOffenders: 0 },
    { borough: "Queens", activeOutages: 1, atRiskStops: 1, chronicOffenders: 0 },
    { borough: "Staten Island", activeOutages: 0, atRiskStops: 0, chronicOffenders: 0 },
  ],
  outagesTrend: [
    { date: "Jun 21", outages: 18 },
    { date: "Jun 22", outages: 21 },
    { date: "Jun 23", outages: 19 },
    { date: "Jun 24", outages: 24 },
    { date: "Jun 25", outages: 28 },
    { date: "Jun 26", outages: 31 },
    { date: "Jun 27", outages: 27 },
  ],
  heatForecast: {
    isHeatWeek: true,
    daysAbove90: 4,
    peakTempF: 96.2,
    forecast: [
      { date: "2026-06-27", tempMaxF: 94.3, isHeatDay: true },
      { date: "2026-06-28", tempMaxF: 96.2, isHeatDay: true },
      { date: "2026-06-29", tempMaxF: 88.1, isHeatDay: false },
      { date: "2026-06-30", tempMaxF: 91.4, isHeatDay: true },
      { date: "2026-07-01", tempMaxF: 92.7, isHeatDay: true },
      { date: "2026-07-02", tempMaxF: 87.9, isHeatDay: false },
      { date: "2026-07-03", tempMaxF: 84.5, isHeatDay: false },
    ],
  },
};

export function buildAtRiskStops(): AtRiskStop[] {
  return alerts
    .map((alert): AtRiskStop | null => {
      const stop = stops.find((s) => s.id === alert.stopId);
      const outage = outages.find((o) => o.id === alert.outageId);
      if (!stop || !outage) return null;
      const provider = providers.find((p) => p.id === stop.providerId);
      if (!provider) return null;
      return { stop, alert, outage, provider };
    })
    .filter((entry): entry is AtRiskStop => entry !== null)
    .sort((a, b) => severityRank(b.alert.severity) - severityRank(a.alert.severity));
}

function severityRank(severity: ProximityAlert["severity"]): number {
  return { critical: 3, warning: 2, watch: 1 }[severity];
}
