# Generated by Django 5.2.15 on 2026-07-01 03:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_data_minimization"),
    ]

    operations = [
        migrations.AddField(
            model_name="routestop",
            name="borough",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="routestop",
            name="floor",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="routestop",
            name="provider_id",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="routestop",
            name="recipient_name",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="routestop",
            name="scheduled_time",
            field=models.CharField(blank=True, default="", max_length=5),
        ),
    ]
